version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: market
      POSTGRES_PASSWORD: market
      POSTGRES_DB: market
    ports:
      - '5436:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
