
spring:
  application:
    name: market
  datasource:
    url: jdbc:postgresql://localhost:5436/market
    username: market
    password: market
  flyway:
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:postgresql://localhost:5436/market
    username: market
    password: market

  rabbitmq:
    host: localhost
    port: 5672
    username: closeSea
    password: closeSeaP@ssword
server:
  port: 8085

wallet:
  uri: "http://localhost:8083"